import os

DATASET_CHANGES_PATH = F''
COMMON_SYMBOLS_PATH = F''
COMMON_INTERVALS_PATH = F''
COMMON_PERIODS_PATH = F''

DATASETDEF_FOLDER = F''
DATA_FOLDER = F''
RESULTS_FOLDER = F''
TESTS_FOLDER = F''
ROBOTS_FOLDER = F''
BUILDER_FOLDER = F''

ROOT = F''
STATIC = F'{os.getcwd()}'